apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_MODE: prod
  LOG_LEVEL: info
  # Multi-line file content:
  app.conf: |
    server {
      listen 80;
    }
