apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-job
  namespace: default
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid        # Allow | Forbid | Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: reporter
            image: busybox
            command: ["sh", "-c", "echo report && date"]
            resources:
              requests:
                cpu: "50m"
                memory: "32Mi"
