apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce     # RWO: one node r/w | ROX: many nodes read-only | RWX: many nodes r/w
  storageClassName: standard   # omit to use cluster default
  resources:
    requests:
      storage: 1Gi